import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";



const AdminPage: NextPage = () => {

const helpRequestsQuery = api.helpRequest.getHelpRequests.useQuery();

const handleHelpRequestClicked = () => {
    console.log('clicked')
   helpRequestsQuery.data?.map((helpRequest => ( 
         console.log(helpRequest.id)
    )))
}

  return (
    <>
      <Head>
        <title>Admin Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col from-[#2e026d] to-[#15162c]">
          <h1 className="text-xl ">Admin Page</h1>
        
        <section>
          <div>
            <table>
                {helpRequestsQuery.data?.map((helpRequest => (
     <button onClick={handleHelpRequestClicked} key={helpRequest.id}>{helpRequest.id}</button>
)))}
 
            </table>
            </div>
            <div>
                <input type="text" ></input>
            </div>
        </section>
      </main>
    </>
  );
};

export default AdminPage;
