import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { HelpWidget } from "../components/HelpWidget";

import { api } from "../utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center from-[#2e026d] to-[#15162c]">
          <h1 className="text-5xl font-extrabold tracking-tight text-grey-600">
            New <span className="text-purple-300">T3ST</span> Build
          </h1>
        <HelpWidget /> 
      </main>
    </>
  );
};

export default Home;
