import { type NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import { HelpWidget } from "../components/HelpWidget";

import { api } from "../utils/api";
import productView from "./productView";
import cartView from "./cartView";

const Home: NextPage = () => {
const router = useRouter();

  return (
        <>
          <Head>
            <title>T3ST App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="flex flex-col items-center justify-center from-[#2e026d] to-[#15162c]">
              <h1 className="text-5xl p-7 font-extrabold tracking-tight text-grey-600">
                New <span className="text-purple-300">T3ST</span> Build
              </h1>
              <div className="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
          <div className="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        <a href="#" >
            <img className="p-8 rounded-t-lg" src="" alt="product image" onClick={() => router.push('/productView')} />
        </a>
        <div className="px-5 pb-5">
            <a href="#">
                <h5 className="text-xl font-semibold tracking-tight text-gray-900 dark:text-white" onClick={() => router.push('/productView')}>Apple Watch Series 7 GPS, Aluminium Case, Starlight Sport</h5>
            </a>
            <div className="flex items-center mt-2.5 mb-5">

            </div>
            <div className="flex items-center justify-between">
                <span className="text-3xl font-bold text-gray-900 dark:text-white" onClick={() => router.push('/productView')}>$599</span>
                <a href="#" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" onClick={() => router.push('/cartView')}>Add to cart</a>
            </div>
        </div>
    </div>
    <div className="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700" onClick={() => router.push('/productView')}>
        <a href="#">
            <img className="p-8 rounded-t-lg" src="" alt="product image" />
        </a>
        <div className="px-5 pb-5">
            <a href="#">
                <h5 className="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">Apple Watch Series 7 GPS, Aluminium Case, Starlight Sport</h5>
            </a>
            <div className="flex items-center mt-2.5 mb-5">
             
            </div>
            <div className="flex items-center justify-between">
                <span className="text-3xl font-bold text-gray-900 dark:text-white" onClick={() => router.push('/productView')}>$599</span>
                <a href="#" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" onClick={() => router.push('/cartView')}>Add to cart</a>
            </div>
        </div>
    </div>
  </div>
        <HelpWidget /> 
      </main>
    </>
  );
};

export default Home;
